modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - funlen
    - goerr113
    - gofumpt
    - exhaustivestruct
    - scopelint
    - makezero
    - golint
    - interfacer
    - maligned

linters-settings:
  gomnd:
    settings:
      mnd:
        checks: [case, condition, return]
  cyclop:
    max-complexity: 15


issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - testpackage
        - paralleltest
        - maligned
        - dupl
    - linters:
        - gosec
      text: "G401: "
    - linters:
        - gosec
      text: "G505: "
