name: GitHub Actions Workflow
on: [push]
jobs:
  fmt:
    name: Fmt
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.3'
      - name: Fmt
        run: go fmt github.com/pavel-v-chernykh/keystore-go/v4/...
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          args: --timeout=5m0s -c .golangci.yaml
          version: v1.43
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.3'
      - name: Test
        run: go test -cover -count=1 -v github.com/pavel-v-chernykh/keystore-go/v4/...
